### ISSUE TITLE
Workshop and Party

### ISSUE THREAD

**Issue by kiskovi97** [kir-dev/parkett-klub-api#12]
Táblák elérése hiányzik

**Comment by OmTheTurtle** [comment]
Egy workshop-hoz csak egy teacher tartozhat? A Party-nál láttam, hogy írtad, hogy így van.

**Comment by kiskovi97** [comment]
Igen

**Comment by OmTheTurtle** [comment]
A workshop táblában külön is szerepel dance_id és teacher_id, amiket a party_id --> dance_course_id-n keresztül közvetetten is elérünk. Ez nekem duplikációnak tűnik. Vagy a workshop-hoz tartozó dance és teacher lehet más, mint a workshophoz tartozó party dance és teacher-e?

**Comment by kiskovi97** [comment]
A workshopon lehet más a dance_id és a teacher_id függetlenül attól, hogy a hozzá kapcsolódó Party-n mi van
