### ISSUE TITLE
dj_party és band_party táblák

### ISSUE THREAD

**Issue by kiskovi97** [kir-dev/parkett-klub-api#13]
Hiányzó táblák pótlása

**Comment by OmTheTurtle** [comment]
Létrehozáskor és módosításkor a `dj_ids` és `band_ids` mezőkben lehet megadni a kapcsolódó dj-k és band-ek Id-ját egy-egy listában. A válaszban `djs` és `ḃands` mezőkben pedig visszajön a kapcsolódó modellek minden tulajdonsága.

**Comment by kiskovi97** [comment]
Az a gond, hogy így szerkesztéskor nem tudom lekérni, hogy milyen bandek és djk lettek kiválasztva. Csak név-url párost ad vissa a bands menü. Vagy a bands és a djs visszaadásakor az id is jelenjen meg mellettük, vagy szimplán csak id-kat adjatok vissza, mert szerkeszteni csak úgy lehet

**Comment by kiskovi97** [comment]
inkább a bands és a djs elemeiben legyen benne az id, úgy könnyebb majd kezelni
