### ISSUE TITLE
Party választható mezők

### ISSUE THREAD

**Issue by kiskovi97** [kir-dev/parkett-klub-api#14]
A Party és Workshop táblánál jó lenne, ha lehetne valahogy jelezni a frontendnek a backend felé, hogy ha egy adott idegen kulcs még nincs megadva (Pl.: Workshophoz nincs megadva tánctanár)

**Comment by OmTheTurtle** [comment]
Be lehet állítani, hogy opcionálisak legyenek az idegen kulcsok (ilyenkor nem is kell leküldeni az adott mezőt). Az említett két táblánál mindegyik idegen kulcs legyen választható, vagy van olyan, aminek mindig lesz / legyen értéke?

**Comment by kiskovi97** [comment]
Mindkét táblában legyen választható!

**Comment by kiskovi97** [comment]
Mindkét táblában minden idegen kulcs legyen választható!
