### ISSUE TITLE
BSS és SPOT Cover fotó tárolása

### ISSUE THREAD

**Issue by kiskovi97** [kir-dev/parkett-klub-api#16]
Amíg nincs bss és spot api, addig le kellene tárolni a backenden a SPOT és BSS linkek mellé a cover fotót is. Ehhez lehetne külön 2 tábla, de lehet akár csak egy mező a pluszban a party-nál

**Comment by OmTheTurtle** [comment]
Várható, hogy más modellnél is kelleni fognak ezek a mezők?

**Comment by kiskovi97** [comment]
Egyenlőre semmi erre utaló jel nincs. Csak a Party-ra szoktunk SPOT-ot és BSS-t hívni

**Comment by OmTheTurtle** [comment]
Rendben. És még egy kérdés, két külön kép legyen a spotnak és bss-nek?

**Comment by kiskovi97** [comment]
Igen

**Comment by kiskovi97** [comment]
Valami nem működik. Nem ad vissza ilyen mezőt GET-eléskor
