### ISSUE TITLE
Cross-Origin Resource Sharing

### ISSUE THREAD

**Issue by kiskovi97** [kir-dev/parkett-klub-api#17]
Ahhoz hogy frontenden lehessen DELETE-t implementálni ahhoz a backendnek is fel kell készülnie OPTIONS fogadására és az arra való válaszra. Ha meg ez le lenne implementálva kérlek irjátok meg, h mit kell frontenden babrálnom, hogy működjön mégis.

**Comment by OmTheTurtle** [comment]
Teszteltem localban Postman-nel és működik a delete (delete request a <model>/:id URL-re), csak 204 No Content-et ad vissza az API default.

**Comment by kiskovi97** [comment]
SoapUI-al nekem is működik, de ha CORS szabályait betartjuk nem engedi a böngésző

**Comment by OmTheTurtle** [comment]
Próbáljátok most, elvileg engedélyeztem a delete-et is.

**Comment by kiskovi97** [comment]
Access to fetch at 'https://parkett-klub.herokuapp.com/members/2' from origin 'https://parkett.netlify.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by OmTheTurtle** [comment]
Lehet hogy amikor próbáltad, még nem végzett a herokus build. Most küldtem postmannel a heroku-ra pár kérést és tudtam törölni a bands-ből.

**Comment by kiskovi97** [comment]
Működik köszi :)
