### ISSUE TITLE
Login teszt, netlify és végleges redirect

### ISSUE THREAD

**Issue by kiskovi97** [kir-dev/parkett-klub-api#21]
Van rá mód, hogy a belépés utáni visszairányításnál lehessen lehetőségként megadni, hogy most épp tesztkörnyezetben vagyunk, vagy netlify környezetben (https://parkett.netlify.com/) vagy a végső parkettklub.ch.bme.hu oldalon? Ezt valahogy paraméterként át lehetne adni, vagy ilyesmi.

**Comment by kiralybalint** [comment]
Hello!
Depoyoltam egy olyan kornyezetet, ami netlify-ra iranyit at (
https://parkett-klub-netlify.herokuapp.com/ ). @OmTheTurtle irt hozza seeder-t, szoval hamarosan kerulnek be dumy adatok is. Egyebkent a redirect URL-t en hagynam 'beegetett' kornyezeti valtozoba, a production kornyezetnel majd beallitjuk a parkettklub.sch.bme.hu domaint.

**Comment by kiskovi97** [comment]
És ehhez milyen client_id tartozik? Csak hogy tudjam tesztelni.
