### ISSUE TITLE
Users member_id mező 

### ISSUE THREAD

**Issue by kiskovi97** [kir-dev/parkett-klub-api#22]
A users táblábol hiányzik a member ID mező. (később majd mindenki szerkeszthesse a saját member részét, a user és member összekapcsolást pedig az admin/körvezető(és PRos) végezheti el)

**Comment by kiskovi97** [comment]
Még nem működik elvileg

**Comment by OmTheTurtle** [comment]
Heroku is a #*!@

**Comment by kiskovi97** [comment]
Ezt kérlek nyissátok újra!
