### ISSUE TITLE
Party Teacher

### ISSUE THREAD

**Issue by kiskovi97** [kir-dev/parkett-klub-api#6]
Miért a Party Teacher entitás tárolja a Party-t? Miért nem fordítva?

**Comment by kiralybalint** [comment]
Az N:M kapcsolat miatt. Igy egy partyhoz tartozhat tobb Party Teacher.

**Comment by kiskovi97** [comment]
Egy Party-hoz csak egy Teacher tartozhat (Annak ellenére h mindig két személy, de egyként kezeljük őket)
