### ISSUE TITLE
Dances plusz változó

### ISSUE THREAD

**Issue by kiskovi97** [kir-dev/parkett-klub-api#8]
A Dances entitáshoz egy plusz változó még kéne. Egy egész szám, (fronteden megjelenítés szempontjából fogjuk használni, h melyik tánnccsoportba tartozik). Neve lehete type vagy dance_type

**Comment by kiralybalint** [comment]
Ezt én inkább kezelném backenden, így ha új táncot vagy tánccsoportot kell hozzáadni, akkor azt meg tudja csinálni  felületről.

**Comment by kiskovi97** [comment]
Úgy is jó, de akkor már a tánccsoport entitáshoz lehessen rendelni egy színt és egy svg képet.
